# NOTICE: you must have an .env file (see the .env.template as a reference).
web:
  build: .
  # all env items should be in .env
  env_file: .env
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - db
    - redis

db:
  #https://hub.docker.com/_/postgres/
  image: postgres:9.5

redis:
  #https://hub.docker.com/_/redis/
  image: redis:3.2-alpine
  command: redis-server --appendonly yes
