default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: weston
  password:
  host: 192.168.59.103

development:
  <<: *default
  database: todolist_development

test:
  <<: *default
  database: todolist_test

production:
  <<: *default
  database: todolist_production
  username: todolist
  password: <%= ENV['TODOLIST_DATABASE_PASSWORD'] %>
  host: 127.0.0.1
